[package]
org = "wso2"
name = "oraclefusion_erp_integrations_connector_sample"
version = "0.1.0"
distribution = "2201.13.4"
title = "oraclefusion-erp-integrations-connector-sample"

[build-options]
sticky = true
